config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "users" => redirect("/users/sign_up") #バリデーションエラー時リロードするとエラー回避
  get "posts" => redirect("/posts/new") #バリデーションエラー時リロードするとエラー回避
  root to: "homes#top"
  get 'about'=>"homes#about",as: "about"

  scope module: :public do
    resources :users, only:[:show, :edit, :update, :leave] do
      member do
        patch :withdraw, to: 'users#withdraw', as: 'withdraw'
        get :follows, :followers, :favorite
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :posts, only:[:new, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy] do
        post 'create_reply', on: :member
      end
      
    end
    resources :relationships, only:[:create, :destroy]
    get 'searches/search', to: 'searches#search', as: 'search'
  end

  get 'admin',to:'admin/homes#top'
  namespace :admin do
    resources :categories, only:[:index, :create, :edit, :update, :destroy]
    resources :tags, only:[:index, :create, :edit, :update, :destroy]
    resources :post_tags, only:[:create, :destroy]
    resources :users, only:[:index, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
  
  validates :tag_name, presence: true, uniqueness: true
  
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :is_matching_login_admin
  
  def index
    @tag = Tag.new
    @tags = Tag.all
    @tag_name = flash[:tag_name] || @tag.tag_name
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path, notice: "タグを作成しました。"
    else
      session[:error_message] = @tag.errors.full_messages
      @tags = Tag.all
      # flash.now[:notice] = "タグ作成に失敗しました。"
      render 'index'
    end
  end

  def edit
    @tag = Tag.find(params[:id])
    @tag_name = flash[:tag_name] || @tag.tag_name
    @has_flash_message = flash.present? #フラッシュメッセージを力技で隠すために設置
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tags_path
    else
      session[:error_message] = @tag.errors.full_messages
      flash[:tag_name] = @tag.tag_name
	    redirect_to edit_admin_tag_path(@tag)
    end
  end

  def destroy
    tag = Tag.find(params[:id])  # データ（レコード）を1件取得
    tag.destroy  # データ（レコード）を削除
    redirect_to admin_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_name)
  end

  def is_matching_login_admin
    admin = current_admin
    unless admin && admin.email == "test@email"
      redirect_to root_path
    end
  end

end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class='container pt-5'>
<% if @has_flash_message %>
  <div class="flash_erase"></div><!--フラッシュメッセージを力技で隠すために設置-->
<% end %>
  <div class="row d-flex justify-content-center">
    <div class="col-sm-6" style="border-radius: 5%; background-color: white; border-radius: 20px; border: 2mm ridge rgba(187, 187, 187, .41);">
      <div class="py-3">
        <h3>タグ編集</h3>


        <% object = session[:error_message] %>
        <% if !object.nil? %>
            <div class="alert alert-danger">
              <strong><%= object.count %>件のエラーが出たので変更を保存できませんでした。</strong>
            <ul>
            <% object.each do |msg| %>
              <%# message.each do |msg| %>
                <li><%= msg %></li>
              <%# end %>
            <% end %>
            </ul>
            </div>
        <% end %>
        <% session[:error_message] = nil %>

        <%= form_with model: @tag, url: admin_tag_path(@tag), method: :patch, local: true do |f| %>
          <div class="form-group">
            <%= f.label :tag_name, "タグ名" %>
            <%= f.text_field :tag_name, value: @tag_name, class: 'form-control', style: "width:30%" %>
          </div>
          <div class="form-group">
            <%= f.submit "変更を保存", class: 'btn btn-outline-success' %>
          </div>
        <% end %>

        <%= link_to "タグを削除", admin_tag_path(@tag.id), method: :delete, "data-confirm" => "本当に消しますか?", class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container pt-5">
  
  <div class="row">
    <div class="col-sm-5 py-3" style="border-radius: 5%; background-color: white; border-radius: 20px; border: 2mm ridge rgba(187, 187, 187, .41);">
      
      <h3>タグ一覧・追加</h3>
      <% object = session[:error_message] %>
      <% if !object.nil? %>
          <div class="alert alert-danger">
            <strong><%= object.count %>件のエラーが出たので追加できませんでした。</strong>
          <ul>
          <% object.each do |msg| %>
            <%# message.each do |msg| %>
              <li><%= msg %></li>
            <%# end %>
          <% end %>
          </ul>
          </div>
      <% end %>
      <% session[:error_message] = nil %>
  
      <%= form_with model:@tag, url: admin_tags_path, method: :post, local:true do |f| %>
        <div class="form-group">
          <%= f.label :tag_name, "タグ名" %>
          <%= f.text_field :tag_name, placeholder: "タグ名",  class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "新規登録", class: 'btn btn-outline-success' %>
        </div>
      <% end %>
    </div>
  </div>
  
  <br>
  
  <div class="col-sm">
    <% @tags.each do |tag| %>
      <p class="badge badge-secondary tag-badge">
        #<%= tag.tag_name %>
        <%= link_to  edit_admin_tag_path(tag.id), method: :get, class: "custom-link" do %>
          <i class="fa-solid fa-pen"></i>
        <% end %>
      </p>
    <% end %>
  </div>
    

</div>