config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "users" => redirect("/users/sign_up") #バリデーションエラー時リロードするとエラー回避
  get "posts" => redirect("/posts/new") #バリデーションエラー時リロードするとエラー回避
  root to: "homes#top"
  get 'about'=>"homes#about",as: "about"

  scope module: :public do
    resources :users, only:[:show, :edit, :update, :leave] do
      member do
        patch :withdraw, to: 'users#withdraw', as: 'withdraw'
        get :follows, :followers, :favorite
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :posts, only:[:new, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy] do
        post 'create_reply', on: :member
      end
      
    end
    resources :relationships, only:[:create, :destroy]
    get 'searches/search', to: 'searches#search', as: 'search'
  end

  get 'admin',to:'admin/homes#top'
  namespace :admin do
    resources :categories, only:[:index, :create, :edit, :update, :destroy]
    resources :tags, only:[:index, :create, :edit, :update, :destroy]
    resources :post_tags, only:[:create, :destroy]
    resources :users, only:[:index, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :posts, dependent: :destroy
  
  validates :category_name, presence: true, uniqueness: true
  
  
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :is_matching_login_admin
  
  def index
    @category = Category.new
    @categories = Category.all
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "カテゴリを作成しました。"
    else
      @categories = Category.all
      # flash.now[:notice] = "カテゴリ作成に失敗しました。"
      render 'index'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
    @category_name = flash[:category_name] || @category.category_name
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: "カテゴリを変更しました。"
    else
      session[:error_message] = @category.errors.full_messages
      flash[:category_name] = @category.category_name
      redirect_to edit_admin_category_path(@category)
    end
  end
  
  private

  def category_params
    params.require(:category).permit(:category_name)
  end
  
  def is_matching_login_admin
    admin = current_admin
    unless admin && admin.email == "test@email"
      redirect_to root_path
    end
  end
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class='container pt-5'>
  <div class="row d-flex justify-content-center">
    <div class="col-sm-6" style="border-radius: 5%; background-color: white; border-radius: 20px; border: 2mm ridge rgba(187, 187, 187, .41);">
      <div class="py-3">
        <h3>カテゴリ編集</h3>
        <% object = session[:error_message] %>
        <% if !object.nil? %>
            <div class="alert alert-danger">
              <strong><%= object.count %>件のエラーが出たので変更を保存できませんでした。</strong>
            <ul>
            <% object.each do |msg| %>
              <%# message.each do |msg| %>
                <li><%= msg %></li>
              <%# end %>
            <% end %>
            </ul>
            </div>
        <% end %>
        <% session[:error_message] = nil %>
        <%= form_with model: @category, url: admin_category_path(@category), method: :patch, local:true do |f| %>
          <div class="form-group">
            <%= f.label :category_name, "カテゴリ名" %>
            <%= f.text_field :category_name, value: @category_name, class: 'form-control', style: "width:30%" %>
          </div>
          <div class="form-group">
            <%= f.submit "変更を保存", class: 'btn btn-outline-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-sm-5 py-3" style="border-radius: 5%; background-color: white; border-radius: 20px; border: 2mm ridge rgba(187, 187, 187, .41);">
      <h3>カテゴリ一覧・追加</h3>
      <% if @category.errors.any? %>
      <div class="alert alert-danger">
        <strong><%= @category.errors.count %>件のエラーが出たので登録できませんでした。</strong>
        <ul>
          <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end%>
        </ul>
      </div>
      <% end %>
    
      <%= form_with model:@category, url: admin_categories_path, method: :post, local:true do |f| %>
        <div class="form-group">
          <%= f.label :category_name, "カテゴリ名" %>
          <%= f.text_field :category_name, placeholder: "カテゴリ名",  class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "新規登録", class: 'btn btn-outline-success' %>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <br>
  <table class='table table-hover table-inverse'>
    <thead class="thead-light">
      <tr>
       <th>カテゴリ</th>
       <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr class="table-light">
          <td><%= category.category_name %></td>
          <td><%= link_to "編集する", edit_admin_category_path(category.id), method: :get, class: 'btn btn-outline-dark' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>