config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "users" => redirect("/users/sign_up") #バリデーションエラー時リロードするとエラー回避
  get "posts" => redirect("/posts/new") #バリデーションエラー時リロードするとエラー回避
  root to: "homes#top"
  get 'about'=>"homes#about",as: "about"

  scope module: :public do
    resources :users, only:[:show, :edit, :update, :leave] do
      member do
        patch :withdraw, to: 'users#withdraw', as: 'withdraw'
        get :follows, :followers, :favorite
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :posts, only:[:new, :show, :edit, :create, :update, :destroy] do
      resource :favorites, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy] do
        post 'create_reply', on: :member
      end
      
    end
    resources :relationships, only:[:create, :destroy]
    get 'searches/search', to: 'searches#search', as: 'search'
  end

  get 'admin',to:'admin/homes#top'
  namespace :admin do
    resources :categories, only:[:index, :create, :edit, :update, :destroy]
    resources :tags, only:[:index, :create, :edit, :update, :destroy]
    resources :post_tags, only:[:create, :destroy]
    resources :users, only:[:index, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_message.html.erb
<div class="container">
  <div class="row justify-content-center pt-5">
    <div class="col-md-6">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> text-center"><%= message %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer" style="border-top: 4mm ridge rgba(255, 255, 255, .2); background-color: #b6e5ff;">

  <div class="container mt-3">
    <div class="row justify-content-center mt-4">
    <%= link_to about_path, class: 'font-weight-bolder' do %>
      <h2>About</h2>
    <% end %>
    <br>
    <br>
    </div>
    <div class="row justify-content-center">
      <%= audio_tag "New_Composition.mp3", controls: true %>
    </div>
    <div class="row">
     <p class="mx-auto font-weight-bolder" style="font-family: 'OCRB'">CopyRight Dokuro Tenshi</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header style="border-bottom: 4mm ridge rgba(187, 187, 187, .41); background-color: #fff;" >
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-sm-2 center-logo">
        <a class="navbar-brand pl-5" href="/"><%= image_tag 'f1006_4.png', size: '120x100' %></a>
      </div>
      <div class="col-sm-4 right-align">
        <% if user_signed_in? %>
          ようこそ、<%= current_user.name %>さん
        <% end %>
      </div>

      <div class="col-sm-6">
        <nav class="navbar navbar-expand-lg navbar-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
  <!--userログイン時-->
          <% if user_signed_in? %>
            <li class="post">
              <%= link_to new_post_path, class: 'nav-link font-weight-bolder' do %>
                <i class="fa-solid fa-circle-plus"></i> 投稿
              <% end %>
            </li>
            <li class="special-li">
              <div class="mypage-btn-container" id="mypageBtnContainer">
                <div class="mx-4"><%= image_tag current_user.get_profile_image, size:'50x50', style: 'border-radius: 50%; overflow: hidden; background-color:#ffffff; border: 2px solid #a9a9a9;' %></div>
                <div class="mypage-dropdown" id="mypageDropdown">
                	<ul>
                	  <li class="py-2"><%= link_to 'マイページ', user_path(current_user) %></li>
                	  <li class="py-2"><%= link_to 'お気に入り', favorite_user_path(current_user) %></li>
                	  <li class="py-2"><%= link_to 'フォロー一覧', follows_user_path(current_user) %></li>
                	  <li class="py-2"><%= link_to 'フォロワー一覧', followers_user_path(current_user) %></li>
                	  <li class="py-2"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                	  <li class="py-2"><%= link_to "退会する", withdraw_user_path(current_user), method: :patch, "data-confirm" => "OKを押すと退会処理がされます。投稿した記事やコメントが削除されます。本当によろしいですか？" %></li>
                	</ul>
                </div>
              </div>
            </li>
  <!--adminログイン時-->
          <% elsif admin_signed_in? %>
            <ul class="navbar-nav custom_row">
              <li>
                <%= link_to admin_users_path, class: 'nav-link font-weight-bolder custom_link' do %>
                  <i class="fa-solid fa-user"></i> ユーザー
                <% end %>
              </li>
              <li>
                <%= link_to admin_categories_path, class: 'nav-link font-weight-bolder custom_link' do %>
                  <i class="fa-solid fa-layer-group"></i> カテゴリ
                <% end %>
              </li>
              <li>
                <%= link_to admin_tags_path, class: 'nav-link font-weight-bolder custom_link' do %>
                  <i class="fa-solid fa-tags"></i> タグ
                <% end %>
              </li>
              <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link font-weight-bolder custom_link' do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>
            </ul>
  <!--ログアウト時-->
          <% else %>
            <li>
              <%= link_to users_guest_sign_in_path, class: "nav-link font-weight-bolder custom_link", method: :post  do %>
                <i class="fa-solid fa-key"></i> ゲストログイン
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: 'nav-link font-weight-bolder custom_link' do %>
                <i class="fa-solid fa-pen"></i> 新規登録
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: 'nav-link font-weight-bolder custom_link' do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
              <% end %>
            </li>
          <% end %>
          </ul>
          </div>
        </nav>
  <!--検索窓-->
        <div class="row custom_search">
          <%= form_with url: search_path, local: true, method: :get, class: "search-form" do |f| %>
            <%= f.text_field :keyword, placeholder: "投稿を検索する", value: params[:keyword], class: "search-input" %>
            <%= f.submit "検索", class: "search-btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QOLPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/69453f024f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="responsive" style="margin-top: 110px;"> <!--ヘッダーの高さ分marginを設定-->
    <%= render 'layouts/flash_message' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <div id="grayDisplay"></div>
  </body>

</html>